version: '3.8'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: symfony-products-api-php
    restart: always
    working_dir: /var/www/symfony_products_api
    volumes:
      - .:/var/www/symfony_products_api
  nginx:
    image: nginx:stable-alpine
    container_name: symfony-products-api-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - .:/var/www/symfony_products_api
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    container_name: symfony-products-api-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Oracle01
      MYSQL_DATABASE: symfony_products_api
      MYSQL_USER: symfony
      MYSQL_PASSWORD: Oracle01
    ports:
      - 3306:3306